### ISSUE TITLE
Kibana Milestones Vis 7.3.1 Release

### ISSUE THREAD

**Issue by podlisk** [walterra/kibana-milestones-vis#10]
Hello,
Thank you for your work, the plugin looks interesting and I wanted to try it but my environment is Elasticsearch and Kibana version 7.3.1.
Do you have plans to make a plugin compatible?
Thank you!

**Comment by walterra** [comment]
Hey! Yes, a release is planned. Kibana `7.2.0` had quite some changes how its API works so this update takes a bit more time but I'm working on it.

**Comment by podlisk** [comment]
Hello, these are great news! Anything I could help, please do not hesitate to request.

**Comment by walterra** [comment]
Believe it or not, 7.3.1 is out the door: https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.3.1
