### ISSUE TITLE
Milestones Options have no effect

### ISSUE THREAD

**Issue by chris-gabler** [walterra/kibana-milestones-vis#13]
Hi!
Thanks for a wonderful plugin, but we would really love to enable "Crop time range" option. However, it seems that the visualization doesn't react to any changes to options (apply changes button is inactive). Is this still a to-do?

**Comment by walterra** [comment]
Thanks for filing the issue! Can you please provide a few more details, maybe a screenshot would help to be able to see what you would expect getting to visualize and what you're actually seeing.

**Comment by chris-gabler** [comment]
Hello, it's been several month since I created this issue and it seems that the plugin has improved in the way we needed! What I meant was the following: 
- we set a time frame to -1 month ago till now. If 3 events had happened the day before it would have shown them all at the end of the line.
- "crop time range" option seemed to be just what we needed: we expected it to show the first event at the beginning of the line, this second one in the middle and the third one at the end of the line.
- we couldn't apply this "crop time range" setting because the "apply" button was disabled 

Now I can see that by default it scales to the actual time interval during which it has had events and does not scale to the time period specified if there have been no events at the beginning or at the end of this period. I don't see this "crop time range" option at the Options tab as well.  However, the issue still persists: I tried unchecking "Render Labels" option but cannot apply changes (see the screenshot).
![image](https://user-images.githubusercontent.com/38730284/83756989-7bb57f80-a678-11ea-95a1-e36981b5ccee.png)

**Comment by walterra** [comment]
Thanks for the details! I'll try to pick it up in the upcoming releases.

**Comment by walterra** [comment]
So far I haven't found a way to fix this issue unfortunately. There's a workaround though and in more recent versions of the plugin I added a hint to use the `Refresh` button instead of that `Play` button. Even if you're on an older version without the hint, clicking the `Refresh` button should work for you. Hope that helps!

<img src="https://user-images.githubusercontent.com/230104/89047056-2206c400-d34e-11ea-98d1-4e2b855eca16.png" width="50%" />

**Comment by walterra** [comment]
From version `v7.4.0` onwards the play/update button is working again! https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.4.0
