### ISSUE TITLE
Not compatible with Kibana 7.9.1

### ISSUE THREAD

**Issue by shubham184** [walterra/kibana-milestones-vis#22]

**Comment by tinpll** [comment]
I love this module in Kibana as it really allows you to set filters for interesting events and show them in a timeline fro threat hunting. However, it feels like we are always a step behind with the latest version of Kibana.

**Comment by filou711** [comment]
Hello. I love this plugin in kibana. Do you know when the plugin will be compatible with kibana 7.8 and more ? Best regards

**Comment by rikitakis** [comment]
Do you know when the plugin will be compatible with kibana 7.12 and more?

**Comment by walterra** [comment]
Thanks for your interest in the plugin! The plugin is available for 7.8 now. I definitely plan to do the other updates, unfortunately I cannot give you a time estimate.

**Comment by walterra** [comment]
7.9.1 is now available, thank you for your patience: https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.9.1

Closing this issue since progress on 7.12 will be tracked in #25.
