### ISSUE TITLE
Not compatible with Kibana 7.12.1

### ISSUE THREAD

**Issue by yesnid** [walterra/kibana-milestones-vis#25]
I know its not released for this version of Kibana but I am wondering if there is a plan to have a release for it sometime soon?

**Comment by walterra** [comment]
Thanks for your interest in the plugin! I definitely plan to do the updates, unfortunately I cannot give you a time estimate.

**Comment by walterra** [comment]
Hey, version `7.12.1` is now available: https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.12.1
