### ISSUE TITLE
Milestone Visualisation compatibility with version 7.11.2

### ISSUE THREAD

**Issue by Nikhil1402** [walterra/kibana-milestones-vis#26]
Hi,
We have been using the milestone visualisation however we had a recent migration of Kibana to version 7.11.2
Could we please get it in this version?
Thank you in advance for your response.

Nikhil

**Comment by walterra** [comment]
Thanks for using the plugin, great that it's useful for you! `v7.11.2` is finally available: https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.11.2
