### ISSUE TITLE
title does not appear in plugin v7.9.1 

### ISSUE THREAD

**Issue by pavel-vhive** [walterra/kibana-milestones-vis#27]
Label field set but in timeline no title appears

Kibana v7.9.1
![Screen Shot 2021-12-20 at 14 19 45](https://user-images.githubusercontent.com/96182119/146766291-57a9d9cc-137d-4b38-bf7a-8f7f87b17933.png)

**Comment by walterra** [comment]
You're right I was able to reproduce this. The problem is the plugin doesn't handle nested fields correctly. A workaround until this is fixed could be to use a runtime field that maps `event.name` to something like `event_name`.

**Comment by walterra** [comment]
Was able to fix this for `v7.10.0` in 10a2e4a and 1c943a9.

Release: https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.10.0

**Comment by pavel-vhive** [comment]
Thank you for the support!
