### ISSUE TITLE
Compatible with kibana 7.16.1  ?

### ISSUE THREAD

**Issue by Harshit-Verma** [walterra/kibana-milestones-vis#28]
we upgrade our ELK stack to 7.16.1 , when trying to install we are getting error
"kibanaMilestonesVis [7.12.1] is incompatible with kibana [7.16.1]"

**Comment by walterra** [comment]
Version `v7.16.1` is now available: https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.16.1
