### ISSUE TITLE
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [kibana-milestones-vis]. Expected [6.1.3]; found [6.1.2]

### ISSUE THREAD

**Issue by yasz** [walterra/kibana-milestones-vis#3]
hello teams ,please support the 6.1.3 version, than you !

**Comment by walterra** [comment]
Sorry for the late reply, turns out something was wrong with my GitHub notifications.

I just created a release for `6.1.3`, you can download it here: https://github.com/walterra/kibana-milestones-vis/releases/download/v1.0.0-alpha3/kibana-6.1.3-milestones-vis-1.0.0-alpha3.zip
