### ISSUE TITLE
Plugin Version for Kibana 6.8.0

### ISSUE THREAD

**Issue by karnamonkster** [walterra/kibana-milestones-vis#5]
Could you please confirm if there will be a release compatible with Kibana v6.8.0

**Comment by walterra** [comment]
Hey! Just released `v6.8.0` you can find the download here: https://github.com/walterra/kibana-milestones-vis/releases/tag/v6.8.0

Let me know if it works for you! Would also love to learn about your use case, if you're willing to share, let's catch up on via [twitter.com/walterra](https://twitter.com/walterra)

**Comment by deadzg** [comment]
@walterra I know I have requested you to provide version for 6.7.1, but by then we moved to 6.8.0. 
I have tested it and this works perfectly fine. 
Thanks a lot.
