### ISSUE TITLE
Is there a release compatible with Kibana 6.7.1 ?

### ISSUE THREAD

**Issue by deadzg** [walterra/kibana-milestones-vis#6]
Could you please confirm if there will be a release compatible with Kibana v6.7.1 or any workaround to make it compatible?

**Comment by walterra** [comment]
Just released `v6.7.1`, you can download it here: https://github.com/walterra/kibana-milestones-vis/releases/tag/v6.7.1

Let me know if it works for you! Would also love to learn about your use case, if you're willing to share, let's catch up on via [twitter.com/walterra](https://twitter.com/walterra)
