### ISSUE TITLE
Kibana Milestones Vis 7.2.0 Release


### ISSUE THREAD

**Issue by walterra** [walterra/kibana-milestones-vis#9]
Kibana 7.2.0 API changes: https://www.elastic.co/blog/kibana-plugin-api-changes-in-7-2

**Comment by LeonShiMin** [comment]
Hello @walterra, I'm not sure how i should go about changing the config files from your v7.1.0 release to make this plugin compatible with kibana 7.2.0. Could you please advice? it will be good if you can give a step by step guidance. Much appreciated (:

**Comment by walterra** [comment]
hey, unfortunately it's not just the config files, a lot changed under the hood in kibana and it needs more work to get it running. sorry it's taking such a looong time for this update. i cannot give you a release estimate but it's on my radar.

**Comment by LeonShiMin** [comment]
thank you for the response. I look forward to having the v7.2 soon! It's a very informative visualization that I'd love to have in my dashboard. Cheers!

**Comment by walterra** [comment]
Just released Version 7.2.0! https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.2.0
